#!/bin/bash
QPS=10
SERVER_IP="172.18.11.114"
MAXREQS=30
WARMUPREQS=10
NTHREADS=1

NUM=${CUR_NUM} \
APP_NAME="masstree" \
TBENCH_QPS=${QPS} \
TBENCH_SERVER=${SERVER_IP} \
TBENCH_SERVER_PORT=10002 \
TBENCH_RANDSEED=${RANDOM} \
TBENCH_MAXREQS=${MAXREQS} TBENCH_WARMUPREQS=${WARMUPREQS} \
TBENCH_MINSLEEPNS=10 \
chrt -r 99 \
${CLIENT_DIR}/client/client_process/mttest_client_networked


#TBENCH_RANDSEED=${RANDOM} \
